In [1]:
import torch
import torch.nn.functional as F

In [2]:
x = torch.Tensor([[[[  1,  2,  3,  4,  5],
   					[  6,  7,  8,  9, 10],
   					[ 11, 12, 13, 14, 15],
   					[ 16, 17, 18, 19, 20],
   					[ 21, 22, 23, 24, 25]]]])
y = F.unfold(x,(3,3))
y

tensor([[[ 1.,  2.,  3.,  6.,  7.,  8., 11., 12., 13.],
         [ 2.,  3.,  4.,  7.,  8.,  9., 12., 13., 14.],
         [ 3.,  4.,  5.,  8.,  9., 10., 13., 14., 15.],
         [ 6.,  7.,  8., 11., 12., 13., 16., 17., 18.],
         [ 7.,  8.,  9., 12., 13., 14., 17., 18., 19.],
         [ 8.,  9., 10., 13., 14., 15., 18., 19., 20.],
         [11., 12., 13., 16., 17., 18., 21., 22., 23.],
         [12., 13., 14., 17., 18., 19., 22., 23., 24.],
         [13., 14., 15., 18., 19., 20., 23., 24., 25.]]])

In [3]:
y = F.unfold(x,(2,2))
y

tensor([[[ 1.,  2.,  3.,  4.,  6.,  7.,  8.,  9., 11., 12., 13., 14., 16., 17.,
          18., 19.],
         [ 2.,  3.,  4.,  5.,  7.,  8.,  9., 10., 12., 13., 14., 15., 17., 18.,
          19., 20.],
         [ 6.,  7.,  8.,  9., 11., 12., 13., 14., 16., 17., 18., 19., 21., 22.,
          23., 24.],
         [ 7.,  8.,  9., 10., 12., 13., 14., 15., 17., 18., 19., 20., 22., 23.,
          24., 25.]]])

In [4]:
y = F.unfold(x,(4,4))
y

tensor([[[ 1.,  2.,  6.,  7.],
         [ 2.,  3.,  7.,  8.],
         [ 3.,  4.,  8.,  9.],
         [ 4.,  5.,  9., 10.],
         [ 6.,  7., 11., 12.],
         [ 7.,  8., 12., 13.],
         [ 8.,  9., 13., 14.],
         [ 9., 10., 14., 15.],
         [11., 12., 16., 17.],
         [12., 13., 17., 18.],
         [13., 14., 18., 19.],
         [14., 15., 19., 20.],
         [16., 17., 21., 22.],
         [17., 18., 22., 23.],
         [18., 19., 23., 24.],
         [19., 20., 24., 25.]]])